build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - pip install pytest
  - pip install .
  - git clone --depth=1 https://github.com/atmtools/typhon-testfiles.git
  - "set TYPHONTESTFILES=%cd%\\typhon-testfiles"

test_script:
  - pytest --pyargs typhon

