language: python
python:
  - 3.6
env:
  - RUN_PEP8=0
  - RUN_PEP8=1
matrix:
  allow_failures:
    - env: RUN_PEP8=1
install:
  - pip install .[tests]
script:
  - pytest
  - |
    if [[ "${RUN_PEP8}" == "1" ]]; then
      pip install flake8
      flake8 --statistics
    fi
