language: python
python:
  - 3.6
env:
  - CONFIG=TEST
  - CONFIG=PEP8
matrix:
  fast_finish: true
  allow_failures:
    - env: CONFIG=PEP8
install:
  - pip install .[tests]
script:
  - |
    case ${CONFIG} in
      TEST)
        pytest --pyargs typhon
        ;;
      PEP8)
        pip install flake8
        flake8 --statistics
        ;;
    esac
