name: typhon
dependencies:
        - python>=3.5.1
        - matplotlib>=1.4
        - netCDF4>=1.1.1
        - nose>=1.3.0
        - numexpr
        - numpy>=1.13
        - pandas
        - scikit-learn
        - scipy>=0.15.1
        - setuptools>=0.7.2
        - xarray>=0.10.2
        - numba

