name: Build and test on Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install apt dependencies
      run: |
        sudo add-apt-repository -y ppa:nextgis/ppa
        sudo apt update
        sudo apt-get install libgdal-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython
        pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal -L/usr/local/lib -lgdal"
        pip install .[tests]
    - name: Lint with flake8
      continue-on-error: true
      run: |
        pip install flake8
        flake8 . --statistics || echo "::error::Check flake8 output for errors"
    - name: Test with pytest
      run: |
        git clone --depth=1 https://github.com/atmtools/typhon-testfiles.git
        export TYPHONTESTFILES=$PWD/typhon-testfiles
        pip install pytest
        pytest --pyargs typhon
